version: "3.7"

services:
  sim:
    image: sim
    container_name: sim
    hostname: sim
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sim:/logs
    environment:
      - SCENARIO=$SCENARIO
    cap_add: 
      - NET_ADMIN
    expose:
      - "57832"
    networks:
      leftnet:
        ipv4_address: 192.168.0.2
      rightnet:
        ipv4_address: 192.168.100.2

  server:
    build: ../$SERVER
    image: $SERVER
    container_name: server
    hostname: server
    stdin_open: true
    tty: true
    volumes:
      - ../$SERVER/logs/server:/logs
    environment:
      - ROLE=server
      - SERVER_PARAMS=$SERVER_PARAMS
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    networks:
      rightnet:
        ipv4_address: 192.168.100.100

  client:
    build: ../$CLIENT
    image: $CLIENT
    container_name: client
    hostname: client
    stdin_open: true
    tty: true
    volumes:
      - ../$CLIENT/logs/client:/logs
    environment:
      - ROLE=client
      - CLIENT_PARAMS=$CLIENT_PARAMS
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    networks:
      leftnet:
        ipv4_address: 192.168.0.100

networks:
  leftnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
  rightnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
