version: "3.7"

services:
  sim:
    volumes:
      - $SIM_LOGS:/logs
  server:
    build: ""
    volumes:
      - $WWW:/www
      - $SERVER_LOGS:/logs
    environment:
      - TESTCASE=$TESTCASE
  client:
    build: ""
    volumes:
      - $DOWNLOADS:/downloads
      - $CLIENT_LOGS:/logs
    environment:
      - TESTCASE=$TESTCASE
      - REQUESTS=$REQUESTS
